### ISSUE TITLE
Many errors with the Makefile

### ISSUE THREAD

**Issue by Vayel** [crossbario/crossbarwww#33]
I runned the Makefile commands on Fedora 20 and got many errors:

These commands work:

```
git clone https://github.com/crossbario/crossbarwww
git clone https://github.com/crossbario/crossbar.wiki.git

cd crossbarwww
pew new crossbarwww # Create a virtualenv with Python 2.7

(crossbarwww) [vincent@vincent crossbarwww]$ make requirements 
#pip install scons # fails on Windows, so install manually
pip install taschenmesser
Collecting taschenmesser
  Using cached taschenmesser-0.1.6.zip
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/vincent/.local/share/virtualenvs/crossbarwww/lib/python2.7/site-packages (from taschenmesser)
Installing collected packages: taschenmesser
  Running setup.py install for taschenmesser
Successfully installed taschenmesser-0.1.6
pip install scour
Collecting scour
  Using cached scour-0.30.zip
Installing collected packages: scour
  Running setup.py install for scour
    Installing scour script to /home/vincent/.local/share/virtualenvs/crossbarwww/bin
Successfully installed scour-0.30
pip install boto
Collecting boto
  Using cached boto-2.36.0-py2.py3-none-any.whl
Installing collected packages: boto

Successfully installed boto-2.36.0
pip install flask
Collecting flask
  Using cached Flask-0.10.1.tar.gz
Collecting Werkzeug>=0.7 (from flask)
  Using cached Werkzeug-0.10.1.tar.gz
Collecting Jinja2>=2.4 (from flask)
  Using cached Jinja2-2.7.3.tar.gz
Collecting itsdangerous>=0.21 (from flask)
  Using cached itsdangerous-0.24.tar.gz
Collecting markupsafe (from Jinja2>=2.4->flask)
  Using cached MarkupSafe-0.23.tar.gz
Installing collected packages: markupsafe, itsdangerous, Jinja2, Werkzeug, flask
  Running setup.py install for markupsafe
    building 'markupsafe._speedups' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c markupsafe/_speedups.c -o build/temp.linux-i686-2.7/markupsafe/_speedups.o
    gcc -pthread -shared -Wl,-z,relro build/temp.linux-i686-2.7/markupsafe/_speedups.o -L/usr/lib -lpython2.7 -o build/lib.linux-i686-2.7/markupsafe/_speedups.so
  Running setup.py install for itsdangerous
  Running setup.py install for Jinja2
  Running setup.py install for Werkzeug
  Running setup.py install for flask
Successfully installed Jinja2-2.7.3 Werkzeug-0.10.1 flask-0.10.1 itsdangerous-0.24 markupsafe-0.23
pip install jinja2-highlight
Collecting jinja2-highlight
  Using cached jinja2-highlight-0.6.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /home/vincent/.local/share/virtualenvs/crossbarwww/lib/python2.7/site-packages (from jinja2-highlight)
Collecting Pygments>=1.5 (from jinja2-highlight)
  Using cached Pygments-2.0.2-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /home/vincent/.local/share/virtualenvs/crossbarwww/lib/python2.7/site-packages (from Jinja2>=2.4->jinja2-highlight)
Installing collected packages: Pygments, jinja2-highlight

  Running setup.py install for jinja2-highlight
Successfully installed Pygments-2.0.2 jinja2-highlight-0.6.1
pip install mistune
Collecting mistune
  Using cached mistune-0.5.tar.gz
Installing collected packages: mistune
  Running setup.py install for mistune
Successfully installed mistune-0.5
pip install frozen-flask
Collecting frozen-flask
  Using cached Frozen-Flask-0.11.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Flask>=0.7 in /home/vincent/.local/share/virtualenvs/crossbarwww/lib/python2.7/site-packages (from frozen-flask)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /home/vincent/.local/share/virtualenvs/crossbarwww/lib/python2.7/site-packages (from Flask>=0.7->frozen-flask)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /home/vincent/.local/share/virtualenvs/crossbarwww/lib/python2.7/site-packages (from Flask>=0.7->frozen-flask)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /home/vincent/.local/share/virtualenvs/crossbarwww/lib/python2.7/site-packages (from Flask>=0.7->frozen-flask)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /home/vincent/.local/share/virtualenvs/crossbarwww/lib/python2.7/site-packages (from Jinja2>=2.4->Flask>=0.7->frozen-flask)
Installing collected packages: frozen-flask
  Running setup.py install for frozen-flask
Successfully installed frozen-flask-0.11

```

Then, errors:

```
(crossbarwww) [vincent@vincent crossbarwww]$ pip install scons
Collecting scons
  Using cached SCons-2.3.0.tar.gz
Installing collected packages: scons
  Running setup.py install for scons
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    error: option --single-version-externally-managed not recognized
    Complete output from command /home/vincent/.local/share/virtualenvs/crossbarwww/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-b2BDMn/scons/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_MUiE0-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/vincent/.local/share/virtualenvs/crossbarwww/include/site/python2.7:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
    
       or: -c --help [cmd1 cmd2 ...]
    
       or: -c --help-commands
    
       or: -c cmd --help
    
    
    
    error: option --single-version-externally-managed not recognized
    
    ----------------------------------------
    Command "/home/vincent/.local/share/virtualenvs/crossbarwww/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-b2BDMn/scons/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_MUiE0-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/vincent/.local/share/virtualenvs/crossbarwww/include/site/python2.7" failed with error code 1 in /tmp/pip-build-b2BDMn/scons

(crossbarwww) [vincent@vincent crossbarwww]$ sudo yum install scons # Works
```

```
(crossbarwww) [vincent@vincent crossbarwww]$ make freeze 
python website/crossbario/__init__.py -f
processed 104 files: 104 ok, 0 error
Traceback (most recent call last):
  File "website/crossbario/__init__.py", line 357, in <module>
    freezer.freeze()
  File "/home/vincent/.local/share/virtualenvs/crossbarwww/lib/python2.7/site-packages/flask_frozen/__init__.py", line 149, in freeze
    new_filename = self._build_one(url)
  File "/home/vincent/.local/share/virtualenvs/crossbarwww/lib/python2.7/site-packages/flask_frozen/__init__.py", line 263, in _build_one
    % (response.status, url))
ValueError: Unexpected status '500 INTERNAL SERVER ERROR' on URL /docs/Adding-Real-Time-to-Django-Applications/
make: *** [freeze] Error 1
```

```
(crossbarwww) [vincent@vincent crossbarwww]$ make clean
rm -rf website/crossbario/build
rm -rf website/crossbario/build_uploaded
scons -uc
scons: Reading SConscript files ...
ImportError: No module named taschenmesser:
  File "/home/vincent/Documents/Prog/crossbar/crossbarwww/SConstruct", line 86:
    taschenmesser = pkg_resources.resource_filename('taschenmesser', '..')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1078:
    return get_provider(package_or_requirement).get_resource_filename(
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 345:
    __import__(moduleOrReq)
make: *** [clean] Error 2
```

```
(crossbarwww) [vincent@vincent crossbarwww]$ python
Python 2.7.5 (default, Feb 19 2014, 13:47:40) 
[GCC 4.8.2 20131212 (Red Hat 4.8.2-7)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import taschenmesser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vincent/.local/share/virtualenvs/crossbarwww/lib/python2.7/site-packages/taschenmesser/__init__.py", line 20, in <module>
    import aws
  File "/home/vincent/.local/share/virtualenvs/crossbarwww/lib/python2.7/site-packages/taschenmesser/aws.py", line 32, in <module>
    _old_match_hostname = ssl.match_hostname
AttributeError: 'module' object has no attribute 'match_hostname'
>>> 
```

**Comment by goeddea** [comment]
- **Install SCons** - tried on Ubuntu, and this fails. Solution: do  `pip install --egg scons` (see http://stackoverflow.com/a/19697682/1077987) - this fixes problems with `make clean`

- **make freeze**: The error was down to non-7bit-ASCII characters in the  page 'Adding-Real-Time-to-Django-Applications.md' (some ASCII art) - fixed this - see also #32

- no idea about the import error in Python (not a Python user), but Taschenmesser does what it's supposed to do
